# ==============================================================================
# HYPRTOOLKIT CONFIGURATION (Sweet Neon Theme)
# ==============================================================================

background       = 0xFF1F1A24
base             = 0xFF282330
text             = 0xFFF8F8F2
alternate_base   = 0xFF18141D
bright_text      = 0xFFFFFFFF
accent           = 0xFFFF79C6
accent_secondary = 0xFF00F5D4

h1_size         = 19
h2_size         = 15
h3_size         = 13
font_size       = 11
small_font_size = 10

icon_theme = candy-icons
